---
openapi: "3.0.3"
info:
  version: 2.2.1
  title: OCPI commands module
  description: Specification for OCPIs commands handlers
paths:
  /ocpi/commands/{command}:
    post:
      description: "Send a command to the CPO, requesting the CPO to send \
      \ the command to the Charge Point"
      parameters:
        - in: query
          name: command
          schema:
            type: string
            enum: ["CANCEL_RESERVATION", "RESERVE_NOW", "START_SESSION", "STOP_SESSION", "UNLOCK_CONNECTOR"]
          description: "Type of command that is requested."
      requestBody:
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/cancelReservation'
                - $ref: '#/components/schemas/reserveNow'
                - $ref: '#/components/schemas/startSession'
                - $ref: '#/components/schemas/stopSession'
                - $ref: '#/components/schemas/unlockConnector'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commandResponse'
          description: commandResponse
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericError'
          description: genericError
      summary: Send a command
  /ocpi/commands/{command}/{uid}:
    post:
      description: "It is up to the implementation of the eMSP to determine \
      \ what parameters are put in the URL. The eMSP sends a URL in the POST \
      \ method body to the CPO. The CPO is required to use this URL for the \
      \ asynchronous response by the Charge Point. It is advised to make this \
      \ URL unique for every request to differentiate simultaneous commands, \
      \ for example by adding a unique id as a URL segment."
      requestBody:
        description: "Result of the command request, from the Charge Point."
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/commandResult'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/commandResponse'
          description: commandResponse
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericError'
          description: genericError
      summary: Receive the asynchronous response from the Charge Point.
components:
  schemas:
    cancelReservation:
      type: object
      properties:
        response_url:
          type: string
        reservation_id:
          type: string
      required:
        - response_url
        - reservation_id
    reserveNow:
      type: object
      properties:
        response_url:
          type: string
        token:
          $ref: '#/components/schemas/token'
        expiry_date:
          type: string
        reservation_id:
          type: string
        location_id:
          type: string
          example: "1234"
        evse_uid:
          type: string
          example: "3256"
        authorization_reference:
          type: string
          example: "567890"
      required:
        - response_url
        - token
        - expiry_date
        - reservation_id
        - location_id
    startSession:
      type: object
      properties:
        response_url:
          type: string
        token:
          $ref: '#/components/schemas/token'
        location_id:
          type: string
        evse_uid:
          type: string
          example: "3256"
        connector_id:
          type: string
          example: "1"
        authorization_reference:
          type: string
          example: "567890"
      required:
        - response_url
        - token
        - location_id
    stopSession:
      type: object
      properties:
        response_url:
          type: string
        session_id:
          type: string
      required:
        - response_url
        - sessions_id
    unlockConnector:
      type: object
      properties:
        response_url:
          type: string
        location_id:
          type: string
        evse_uid:
          type: string
          example: "3256"
        connector_id:
          type: string
          example: "1"
      required:
        - response_url
        - location_id
        - evse_uid
        - connector_id
    token:
      type: object
      properties:
        country_code:
          type: string
          example: "DE"
        party_id:
          type: string
          example: "TNM"
        uid:
          type: string
          example: "bdf21bce-fc97-11e8-8eb2-f2801f1b9fd1"
        type:
          type: string
          enum: ["AD_HOC_USER", "APP_USER", "OTHER", "RFID"]
        contract_id:
          type: string
          example: "DE8ACC12E46L89"
        visual_number:
          type: string
          example: "DF000-2001-8999-1"
        issuer:
          type: string
          example: "TheNewMotion"
        group_id:
          type: string
          example: "DF000-2001-8999"
        valid:
          type: boolean
          example: true
        whitelist:
          type: string
          enum: ["ALWAYS", "ALLOWED", "ALLOWED_OFFLINE", "NEVER"]
        language:
          type: string
          example: "en"
        default_profile_type:
          type: string
          enum: ["CHEAP", "FAST", "GREEN", "REGULAR"]
        energy_contract:
          type: object
          properties:
            supplier_name:
              type: string
              example: "Greenpeace Energy eG"
            contract_id:
              type: string
              example: "0123456789"
          required:
            - supplier_name
        last_updated:
          type: string
          example: "2018-12-10T17:25:10Z"
      required:
        - country_code
        - party_id
        - uid
        - type
        - contract_id
        - issuer
        - valid
        - whitelist
        - last_updated
    commandResponse:
      type: object
      properties:
        result:
          type: string
          enum: ["NOT_SUPPORTED", "REJECTED", "ACCEPTED", "UNKNOWN_SESSION"]
        timeout:
          type: integer
          example: 0
        message:
          type: object
          properties:
            language:
              type: string
              example: "en"
            text:
              type: string
          required:
            - language
            - text
      required:
        - result
        - timeout
    commandResult:
      type: object
      properties:
        result:
          type: string
          enum: ["ACCEPTED", "CANCELED_RESERVATION", "EVSE_OCCUPIED", "EVSE_INOPERATIVE", "FAILED", "NOT_SUPPORTED", "REJECTED", "TIMEOUT", "UNKNOWN_RESERVATION"]
        message:
          type: object
          properties:
            language:
              type: string
              example: "en"
            text:
              type: string
          required:
            - language
            - text
      required:
        - result
    genericError:
      type: object
      properties:
        status_code:
          type: number
          example: 2001
        status_message:
          type: string
          example: "Missing required field: type"
        timeStamp:
          type: string
          example: "2015-06-30T21:59:59Z"
      required:
        - status_code
        - timeStamp

