---
openapi: "3.0.3"
info:
  version: 2.2.1
  title: OCPI versions module
  description: Specification for OCPIs versions handlers
paths:
  /ocpi/versions:
    get:
      description: "Fetch information about the supported versions."
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/versions'
          description: versions
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericError'
          description: genericError
      summary: Get supported versions
  /ocpi/2.2.1/details:
    get:
      description: "Fetch information about the supported endpoints for version."
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/details'
          description: details
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/genericError'
          description: genericError
      summary: Get version supported endpoints
components:
  schemas:
    versions:
      type: object
      properties:
        data:
          type: object
          properties:
            version:
              type: string
              enum: ["2.0", "2.1", "2.1.1", "2.2", "2.2.1"]
            url:
              type: string
              example: "https://www.server.com/ocpi/2.2.1/"
          required:
            - version
            - url
        status_code:
          type: number
          example: 1000
        status_message:
          type: string
          example: "Success"
        timeStamp:
          type: string
          example: "2015-06-30T21:59:59Z"
      required:
        - status_code
        - timestamp
    details:
      type: object
      properties:
        data:
          type: object
          properties:
            version:
              type: string
              enum: ["2.0", "2.1", "2.1.1", "2.2", "2.2.1"]
            endpoints:
              type: object
              properties:
                identifier:
                  $ref: '#/components/schemas/moduleIDType'
                role:
                  $ref: '#/components/schemas/interfaceRoleType'
                url:
                  description: "URL to the endpoint."
                  type: string
                  example: "https://example.com/ocpi/2.2.1/cdrs/"
              required:
                - identifier
                - role
                - url
          required:
            - version
        status_code:
          type: number
          example: 1000
        status_message:
          type: string
          example: "Success"
        timeStamp:
          type: string
          example: "2015-06-30T21:59:59Z"
      required:
        - status_code
        - timestamp
    moduleIDType:
      description: "OCPI 2.2.1 modules"
      enum:
      - cdrs
      - chargingprofiles
      - commands
      - credentials
      - hubclientinfo
      - locations
      - sessions
      - tariffs
      - tokens
      type: string
    interfaceRoleType:
      description: "Interface role endpoint implements."
      enum:
      - SENDER
      - RECEIVER
      type: string
    genericError:
      type: object
      properties:
        status_code:
          type: number
          example: 2001
        status_message:
          type: string
          example: "Missing required field: type"
        timeStamp:
          type: string
          example: "2015-06-30T21:59:59Z"
      required:
        - status_code
        - timeStamp



