---
openapi: "3.0.3"
info:
  version: 1.0.0
  title: OCPI CDRs module
  description: Specification for OCPIs CDRs handlers
paths:
  /ocpi/cdrs:
    get:
      description: "Fetch CDRs from the CPO's system"
      parameters:
        - in: query
          name: date_from
          schema:
            type: string
          description: "Return CDRs that have last_updated after or equal to this Date/Time (inclusive)."
        - in: query
          name: date_to
          schema:
            type: string
          description: "Return CDRs that have last_updated up to this Date/Time, but not including (exclusive)."
        - in: query
          name: offset
          schema:
            type: integer
          description: "The offset of the first object returned. Default is 0."
        - in: query
          name: limit
          schema:
            type: integer
          description: "Maximum number of objects to GET."
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cdrsResponse'
          description: cdrsResponse
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorGeneric'
          description: errorGeneric
      summary: Get CDRs
    post:
      description: "Creates a new CDR. The POST method should contain the full and final CDR object. \
      \ Returns URL of created CDR object"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/cdr'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/cdrResponse'
          description: cdrResponse
        default:
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/errorGeneric'
          description: errorGeneric
      summary: Create CDR object
components:
  schemas:
    cdrsResponse:
      type: object
      properties:
        cdrs:
          $ref: '#/components/schemas/cdr'
        status_code:
            type: number
            example: 1000
        status_message:
          type: string
          example: "Success"
        timeStamp:
          type: string
          example: "2015-06-30T21:59:59Z"
      required:
        - status_code
        - timestamp
    cdrResponse:
      type: object
      properties:
        url:
          type: string
          example: "https://www.server.com/ocpi/cdrs/123456"
        status_code:
            type: number
            example: 1000
        status_message:
          type: string
          example: "Success"
        timeStamp:
          type: string
          example: "2015-06-30T21:59:59Z"
      required:
        - url
        - status_code
        - timestamp
    cdr:
      type: object
      properties:
        country_code:
          type: string
          example: "CZ"
        party_id:
          type: string
          example: "BEC"
        id:
          type: string
          example: "12345"
        start_date_time:
          type: string
          example: "2015-06-29T21:39:09Z"
        end_date_time:
          type: string
          example: "2015-06-29T21:39:09Z"
        session_id:
          type: string
          example: "1234"
        cdr_token:
          type: object
          properties:
            country_code:
              type: string
              example: "CZ"
            party_id:
              type: string
              example: "STK"
            uid:
              type: string
              example: "123abc"
            type:
              $ref: '#/components/schemas/tokenType'
            contract_id:
              type: string
              example: "NL-TST-C12345678-S"
          required:
            - country_code
            - party_id
            - uid
            - type
            - contract_id
        auth_method:
          $ref: '#/components/schemas/authMethodType'
        authorization_reference:
          type: string
        cdr_location:
          type: object
          properties:
            id:
              type: string
              example: "LOC1"
            name:
              type: string
              example: "Gent Zuid"
            address:
              type: string
              example: "F.Rooseveltlaan 3A"
            city:
              type: string
              example: "Gent"
            postal_code:
              type: string
              example: "9000"
            state:
              type: string
            country:
              type: string
              example: "BEL"
            coordinates:
              type: object
              properties:
                latitude:
                  type: string
                  example: "51.047599"
                longitude:
                  type: string
                  example: "3.729944"
              required:
                - latitude
                - longitude
            evse_uid:
              type: string
              example: "3256"
            evse_id:
              type: string
              example: "BE*BEC*E041503003"
            connector_id:
              type: string
              example: "1"
            connector_standard:
              $ref: '#/components/schemas/connectorType'
            connector_format:
              $ref: '#/components/schemas/connectorFormatType'
            connector_power_type:
              $ref: '#/components/schemas/powerType'
        meter_id:
          type: string
        currency:
          type: string
          example: "EUR"
        tariffs:
          type: object
          properties:
            country_code:
              type: string
              example: "BE"
            party_id:
              type: string
              example: "BEC"
            id:
              type: string
              example: "12"
            currency:
              type: string
              example: "EUR"
            type:
              $ref: '#/components/schemas/tariffType'
            tariff_alt_text:
              type: object
              properties:
                language:
                  type: string
                  example: "en"
                text:
                  type: string
                  example: "2.00 euro p/hour including VAT."
              required:
                - language
                - text
            tariff_alt_url:
              type: string
              example: "https://company.com/tariffs/14"
            min_price:
              $ref: '#/components/schemas/price'
            max_price:
              $ref: '#/components/schemas/price'
            elements:
              type: object
              properties:
                price_components:
                  $ref: '#/components/schemas/tariffDimensionType'
                restrictions:
                  type: object
                  properties:
                    start_time:
                      type: string
                      example: "09:00"
                    end_time:
                      type: string
                      example: "18:00"
                    start_date:
                      type: string
                      example: "2019-06-23T08:16:02Z"
                    end_date:
                      type: string
                      example: "2015-06-29T23:50:16Z"
                    min_kwh:
                      type: number
                      example: 1.0
                    max_kwh:
                      type: number
                      example: 1.0
                    min_current:
                      type: number
                      example: "32.00"
                    max_current:
                      type: number
                      example: "30"
                    min_power:
                      type: number
                      example: 32.00
                    max_power:
                      type: number
                      example: 32.00
                    min_duration:
                      type: integer
                      example: 0
                    max_duration:
                      type: integer
                      example: 3600
                    day_of_week:
                      $ref: '#/components/schemas/dayOfWeekType'
                    reservation:
                      $ref: '#/components/schemas/reservationRestrictionType'
            start_date_time:
              type: string
              example: "2019-06-23T08:16:02Z"
            end_date_time:
              type: string
              example: "2019-06-23T08:16:02Z"
            energy_mix:
              type: object
              properties:
                is_green_energy:
                  type: boolean
                  example: true
                energy_sources:
                  type: object
                  properties:
                    source:
                      $ref: '#/components/schemas/energySourceCategoryType'
                    percentage:
                      type: number
                      example: "21.7"
                  required:
                    - source
                    - percentage
                environ_impact:
                  type: object
                  properties:
                    category:
                      $ref: '#/components/schemas/environmentalImpactCategoryType'
                    amount:
                      type: number
                      example: 372
                  required:
                    - category
                    - amount
                supplier_name:
                  type: string
                  example: "E.ON Energy Deutschland"
                energy_product_name:
                  type: string
                  example: "E.ON DirektStrom eco"
              required:
                - is_green_energy
            last_updated:
              type: string
              example: "2015-06-29T22:39:09Z"
          required:
            - country_code
            - party_id
            - id
            - currency
            - last_updated
        charging_periods:
          type: object
          properties:
            start_date_time:
              type: string
              example: "2019-06-23T08:16:02Z"
            dimensions:
              type: object
              properties:
                type:
                  $ref: '#/components/schemas/cdrDimensionType'
                volume:
                  type: number
                  example: 2200
              required:
                - type
                - volume
            tariff_id:
              type: string
              example: "12"
          required:
            - start_date_time
        signed_data:
          type: object
          properties:
            encoding_method:
              type: string
            encoding_method_version:
              type: integer
            public_key:
              type: string
            signed_values:
              type: object
              properties:
                nature:
                  type: string
                plain_data:
                  type: string
                signed_data:
                  type: string
              required:
                - nature
                - plain_data
                - signed_data
            url:
              type: string
              example: "https://example.com"
          required:
            - encoding_method
        total_cost:
          $ref: '#/components/schemas/price'
        total_fixed_cost:
          $ref: '#/components/schemas/price'
        total_energy:
          type: number
          example: 15.342
        total_energy_cost:
          $ref: '#/components/schemas/price'
        total_time:
          type: number
          example: 1.973
        total_time_cost:
          $ref: '#/components/schemas/price'
        total_parking_time:
          type: number
        total_parking_cost:
          $ref: '#/components/schemas/price'
        total_reservation_cost:
          $ref: '#/components/schemas/price'
        remark:
          type: string
        invoice_reference_id:
          type: string
        credit:
          type: boolean
          example: true
        credit_reference_id:
          type: string
        home_charging_compensation:
          type: boolean
          example: true
        last_updated:
          type: string
          example: "2015-06-29T22:39:09Z"
      required:
        - country_code
        - party_id
        - id
        - start_date_time
        - end_date_time
        - cdr_token
        - auth_method
        - cdr_location
        - currency
        - total_cost
        - total_energy
        - total_time
        - last_updated
    authMethodType:
      description: "Authentications methods"
      enum:
      - "AUTH_REQUEST"
      - "COMMAND"
      - "WHITELIST"
      type: string
    connectorType:
      description: "The socket or plug standard of the charging point."
      enum:
      - "CHADEMO"
      - "CHAOJI"
      - "DOMESTIC_A"
      - "DOMESTIC_B"
      - "DOMESTIC_C"
      - "DOMESTIC_D"
      - "DOMESTIC_E"
      - "DOMESTIC_F"
      - "DOMESTIC_G"
      - "DOMESTIC_H"
      - "DOMESTIC_J"
      - "DOMESTIC_K"
      - "DOMESTIC_L"
      - "DOMESTIC_M"
      - "DOMESTIC_N"
      - "DOMESTIC_O"
      - "GBT_AC"
      - "GBT_DC"
      - "IEC_60309_2_single_16"
      - "IEC_60309_2_three_16"
      - "IEC_60309_2_three_32"
      - "IEC_60309_2_three_64"
      - "IEC_62196_T1"
      - "IEC_62196_T1_COMBO"
      - "IEC_62196_T2"
      - "IEC_62196_T2_COMBO"
      - "IEC_62196_T3A"
      - "IEC_62196_T3C"
      - "NEMA_5_20"
      - "NEMA_6_30"
      - "NEMA_6_50"
      - "NEMA_10_30"
      - "NEMA_10_50"
      - "NEMA_14_30"
      - "NEMA_14_50"
      - "PANTOGRAPH_BOTTOM_UP"
      - "PANTOGRAPH_TOP_DOWN"
      - "TESLA_R"
      - "TESLA_S"
      type: string
    tokenType:
      description: "Tokens"
      enum:
        - "AD_HOC_USER"
        - "APP_USER"
        - "OTHER"
        - "RFID"
      type: string
    connectorFormatType:
      description: "The format of the connector, whether it is a socket or a plug."
      enum:
      - "SOCKET"
      - "CABLE"
      type: string
    powerType:
      enum:
      - "AC_1_PHASE"
      - "AC_2_PHASE"
      - "AC_2_PHASE_SPLIT"
      - "AC_3_PHASE"
      - "DC"
      type: string
    tariffType:
      enum:
      - "AD_HOC_PAYMENT"
      - "PROFILE_CHEAP"
      - "PROFILE_FAST"
      - "PROFILE_GREEN"
      - "REGULAR"
      type: string
    tariffDimensionType:
      enum:
      - "ENERGY"
      - "FLAT"
      - "PARKING_TIME"
      - "TIME"
      type: string
    dayOfWeekType:
      enum:
      - "MONDAY"
      - "TUESDAY"
      - "WEDNESDAY"
      - "THURSDAY"
      - "FRIDAY"
      - "SATURDAY"
      - "SUNDAY"
      type: string
    reservationRestrictionType:
      enum:
      - "RESERVATION"
      - "RESERVATION_EXPIRES"
      type: string
    energySourceCategoryType:
      description: "Categories of energy sources."
      enum:
      - "NUCLEAR"
      - "GENERAL_FOSSIL"
      - "COAL"
      - "GAS"
      - "GENERAL_GREEN"
      - "SOLAR"
      - "WIND"
      - "WATER"
      type: string
    environmentalImpactCategoryType:
      description: "Categories of environmental impact values"
      enum:
      - "NUCLEAR_WASTE"
      - "CARBON_DIOXIDE"
      type: string
    cdrDimensionType:
      description: "Allowed values for cdr dimensions"
      enum:
      - "CURRENT"
      - "ENERGY"
      - "ENERGY_EXPORT"
      - "ENERGY_IMPORT"
      - "MAX_CURRENT"
      - "MIN_CURRENT"
      - "MAX_POWER"
      - "MIN_POWER"
      - "PARKING_TIME"
      - "POWER"
      - "RESERVATION_TIME"
      - "STATE_OF_CHARGE"
      - "TIME"
      type: string
    price:
      type: object
      properties:
        excl_vat:
          type: number
          example: 2.5
        incl_vat:
          type: number
          example: 0.66
      required:
        - excl_vat
    errorGeneric:
      type: object
      properties:
        status_code:
          type: number
          example: 2001
        status_message:
          type: string
          example: "Missing required field: type"
        timeStamp:
          type: string
          example: "2015-06-30T21:59:59Z"
      required:
        - status_code
        - timeStamp


